version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: quest-res-db-container
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: quest_reservations_db
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"

volumes:
  postgres_data:
