version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: quest-res-db-container
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: quest_reservations_db
      POSTGRES_USER: postgres
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
