spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quest_reservations_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties.hibernate.highlight_sql: true